package io.github.sinri.keel.aigc.api.agent;

import java.time.Instant;
import java.util.Objects;

/**
 * Immutable identity and input of one tool invocation.
 *
 * @param invocationId audit correlation ID generated immediately before execution
 * @param toolCallId    tool call ID generated by the LLM provider
 * @param functionName  requested function name
 * @param arguments     provider-supplied raw JSON argument string
 * @param startedAt     wall-clock start time
 */
public record CatholicToolInvocationObservation(
    String invocationId,
    String toolCallId,
    String functionName,
    String arguments,
    Instant startedAt
) {
    public CatholicToolInvocationObservation {
        Objects.requireNonNull(invocationId, "invocationId");
        Objects.requireNonNull(toolCallId, "toolCallId");
        Objects.requireNonNull(functionName, "functionName");
        Objects.requireNonNull(arguments, "arguments");
        Objects.requireNonNull(startedAt, "startedAt");
    }
}
